### ISSUE TITLE
I get a generic "something went wrong" error page if I search for an offender with last name only

### ISSUE THREAD

**Issue by tmaybe** [multnomah-fellowship/myadvocate#3]
If I submit a search with only the last name filled in, I get a generic error page with the message: "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

This is probably a rare occurrence, but it might be nice to have a more instructional error message, or, if the application really can't handle a last-name-only search, it shouldn't let you submit one.

**Comment by tdooner** [comment]
Interesting, instead of it showing the "no results" error it raises a `OosMechanizer::Searcher::NoPaginationError`
(https://github.com/tdooner/oos-mechanizer/blob/master/lib/oos_mechanizer.rb#L81)

which is an assertion I made that there is always the pagination control on the page if the results table is rendered. Weird. I'll have to dig in and try to reproduce this.

**Comment by tdooner** [comment]
I have improved the error messages, no more 500 errors! (Hopefully...)
